
import { DPRRecord, Project, ProjectTask } from './types';

export const LABOUR_CATEGORIES = [
  'Barbender',
  'Carpenter',
  'Engineer',
  'Helper',
  'Mason',
  'Supervisor'
];

export const MATERIAL_TYPES = [
  { name: 'Cement', unit: 'Bags' },
  { name: 'M-Sand', unit: 'cft' },
  { name: 'Steel', unit: 'kg' },
  { name: 'Bricks', unit: 'nos' },
  { name: 'Solar Panels', unit: 'nos' },
  { name: 'Inverters', unit: 'nos' }
];

export const MATERIAL_INDENT_SUGGESTIONS = [
  'Cement - OPC',
  'Cement - PPC',
  'Cement - PSC',
  'Sand - River sand',
  'Sand - M-sand',
  'Aggregates - 20mm',
  'Aggregates - 40mm',
  'Steel - TMT bars',
  'Steel - Structural steel',
  'Concrete',
  'Ready-Mix Concrete (RMC)',
  'Bricks - Red bricks',
  'Bricks - Fly ash bricks',
  'Blocks - AAC blocks',
  'Blocks - Solid blocks',
  'Blocks - Hollow blocks',
  'Cement mortar',
  'Lime',
  'Stone - Granite',
  'Stone - Rubble stone',
  'Wall putty',
  'Cement plaster',
  'Gypsum plaster',
  'RCC slabs',
  'Roofing sheets - GI',
  'Roofing sheets - Color-coated',
  'Roofing sheets - Polycarbonate',
  'Clay roof tiles',
  'Concrete roof tiles',
  'Floor tiles - Vitrified',
  'Floor tiles - Ceramic',
  'Marble',
  'Granite',
  'Kota stone',
  'Waterproofing membranes',
  'Waterproofing chemicals',
  'Wood',
  'Engineered wood',
  'Plywood',
  'Laminates',
  'Aluminium frames',
  'UPVC frames',
  'Glass - Clear',
  'Glass - Toughened',
  'Glass - Laminated',
  'Door hardware - Hinges',
  'Door hardware - Locks',
  'Door hardware - Handles',
  'Paints - Interior',
  'Paints - Exterior',
  'Paints - Enamel',
  'Primers',
  'Sealers',
  'Tile adhesive',
  'Tile grout',
  'False ceiling - Gypsum boards',
  'False ceiling - Metal grid',
  'Electrical wires & cables',
  'Switches & sockets',
  'Distribution boards',
  'Light fixtures - LED',
  'Light fixtures - Street lights',
  'Earthing materials',
  'Plumbing pipes - PVC',
  'Plumbing pipes - CPVC',
  'Plumbing pipes - UPVC',
  'Plumbing pipes - HDPE',
  'Valves & fittings',
  'Sanitary - WC',
  'Sanitary - Wash basin',
  'Sanitary - Urinal',
  'Water tanks',
  'Pumps',
  'Rainwater harvesting components',
  'Construction admixtures',
  'Curing compounds',
  'Grouts',
  'Sealants',
  'Anti-corrosion coatings',
  'Shuttering - Plywood',
  'Shuttering - MS plates',
  'Scaffolding - Pipes',
  'Scaffolding - Couplers',
  'Binding wire',
  'Nails',
  'Screws',
  'Anchors',
  'Safety - Helmets',
  'Safety - Shoes',
  'Safety - Safety nets'
];

export const PROJECTS_DATA: Project[] = [
  { 
    id: 'p1', 
    name: 'WAAREE', 
    location: 'Chennai Site A', 
    siteEngineer: 'Vivek',
    projectManager: 'Mathiazhagan',
    progress: 15, 
    status: 'On Track' 
  },
  { 
    id: 'p2', 
    name: 'WABAG', 
    location: 'Chennai Site B', 
    siteEngineer: 'Eng. Suresh', 
    projectManager: 'Mathiazhagan',
    progress: 45, 
    status: 'On Track' 
  },
  { 
    id: 'p3', 
    name: 'SRM AP', 
    location: 'Andhra Pradesh', 
    siteEngineer: 'Eng. Priya', 
    projectManager: 'Mathiazhagan',
    progress: 30, 
    status: 'On Track' 
  },
  { 
    id: 'p4', 
    name: 'VIBGYOR', 
    location: 'OMR, Chennai', 
    siteEngineer: 'Eng. Vikram', 
    projectManager: 'Mathiazhagan',
    progress: 60, 
    status: 'On Track' 
  }
];

export const INITIAL_TASKS: ProjectTask[] = [];

export const INITIAL_DPR_DATA: DPRRecord[] = [];
